# ******************************************************************************
#
# cs-hello-world, python hello world project
#
# Copyright 2024-2026 Jeremy A Gray <grayj2@wcslive.com>.
#
# All rights reserved.
#
# ******************************************************************************

[tool]

[tool.doc8]

ignore-path = [
  ".tox",
  ".venv",
  "*.egg-info",
]

[tool.pccc]

header_length = 50
body_length = 72
wrap = true
force_wrap = true
spell_check = false
repair = false
ignore_generated_commits = true

generated_commits = [
  '''^\(tag:\s+v\d+\.\d+\.\d\)\s+\d+\.\d+\.\d+$''',
  '''^Merge branch 'master' of.*$''',
]

types = [
  "depends",
  "docs",
  "feat",
  "fix",
  "perf",
  "refactor",
  "release",
  "style",
  "test",
]

scopes = [
  "hello",
  "tooling",
]

footers = [
  "github-closes",
  "signed-off-by",
]

required_footers = [
  "signed-off-by",
]

[tool.poetry]

authors = ["Jeremy A Gray <grayj2@wcslive.com>"]
description = "python hello world project"
name = "cs-hello-world"
version = "0.0.1"
maintainers = ["Jeremy A Gray <grayj2@wcslive.com>"]
homepage = "https://github.com/jeremy-a-gray/cs-hello-world"
repository = "https://github.com/jeremy-a-gray/cs-hello-world"

packages = [
  { include = "hello" },
]

[tool.poetry.scripts]

hello = "hello:main"

[tool.poetry.dependencies]

python = ">=3.12.1,<4.0"

[tool.poetry.group.dev.dependencies]

doc8 = ">=2"
pccc = ">=0"
pre-commit = ">=3"
pytest = ">=8"
ruff = ">=0"

[tool.pytest.ini_options]

[tool.ruff.lint]

select = [
  "B",
  "C90",
  "D",
  "E",
  "F",
  "RUF",
  "S",
  "W",
]

ignore = [
  "D203",
  "D213",
]

[tool.ruff.lint.per-file-ignores]

"__init__.py" = [ "F401" ]
"tests/test_*.py" = [ "S101", "S311" ]
